default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: study_plan_development


test:
  <<: *default
  database: study_plan_test

production:
  <<: *default
  database: study_plan_production
  username: study_plan
  password: <%= ENV['STUDY_PLAN_DATABASE_PASSWORD'] %>
